"""
Renders an architecture spec + its completion state into a single
Markdown file (ARCHITECTURE.md) that a human can read directly on
GitHub — a Mermaid flowchart of the sections and their dependencies,
plus a flat checklist marking what's done ("+") and what's next ("-").
"""

from __future__ import annotations

from atlas.spec import Spec, SpecNode
from atlas.state import State


def _topological_order(spec: Spec) -> list[SpecNode]:
    """
    Order nodes so every node comes after everything it depends on.
    Assumes spec.validate() has already ruled out cycles.
    """
    visited: set[str] = set()
    order: list[SpecNode] = []

    def visit(node: SpecNode) -> None:
        if node.id in visited:
            return
        visited.add(node.id)
        for dep_id in node.depends_on:
            dep = spec.get(dep_id)
            if dep is not None:
                visit(dep)
        order.append(node)

    for node in spec.nodes:
        visit(node)

    return order

def _status_marker(node: SpecNode, state: State) -> str:
    if state.is_done(node.id):
        return "+"
    if all(state.is_done(dep) for dep in node.depends_on):
        return "-"
    return " "

def render_mermaid(spec: Spec, state: State) -> str:
    lines = ["```mermaid", "flowchart TD"]
    for node in spec.nodes:
        marker = _status_marker(node, state)
        label = f"[{marker}] {node.name}".replace('"', "'")
        lines.append(f'    {node.id}["{label}"]')
    for node in spec.nodes:
        for dep_id in node.depends_on:
            lines.append(f"    {dep_id} --> {node.id}")
    lines.append("```")
    return "\n".join(lines)

def render_checklist(spec: Spec, state: State) -> str:
    lines = []
    for node in _topological_order(spec):
        marker = _status_marker(node, state)
        box = "[x]" if marker == "+" else "[ ]"
        suffix = " (ready to start)" if marker == "-" else ""
        lines.append(f"- {box} **{node.name}**{suffix}")
        if node.description:
            lines.append(f"  {node.description}")
    return "\n".join(lines)

def render_markdown(spec: Spec, state: State) -> str:
    done = len(state.completed_ids())
    total = len(spec.nodes)
    parts = [
        f"# {spec.project_name} — Architecture Map",
        "",
        f"Progress: {done}/{total} sections complete.",
        "",
        "## Flowchart",
        "",
        render_mermaid(spec, state),
        "",
        "## Checklist",
        "",
        render_checklist(spec, state),
        "",
        "_Generated by atlas — do not edit by hand._",
    ]
    return "\n".join(parts) + "\n"